<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_CURA_Login_DataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2f865345-4923-4bdd-bd4c-227acf87b4ff</testSuiteGuid>
   <testCaseLink>
      <guid>8a2bf34e-48f8-4b0f-8f6a-f80304abc57d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CURA_Login_DD</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8867111c-e0e1-4f66-a845-72bc3bc51a87</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CURA_LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8867111c-e0e1-4f66-a845-72bc3bc51a87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>721e7ace-d18a-4795-b5f9-2b7fb5653773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8867111c-e0e1-4f66-a845-72bc3bc51a87</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>32749cf3-7998-4650-b346-29ada4185a79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>744b6277-07ef-491d-85eb-9dbfd4d3695a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CURA_Login_DD</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>721e7ace-d18a-4795-b5f9-2b7fb5653773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32749cf3-7998-4650-b346-29ada4185a79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7cf4323-3286-4912-b90a-b3d3c5003622</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CURA_Login_DD</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>721e7ace-d18a-4795-b5f9-2b7fb5653773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32749cf3-7998-4650-b346-29ada4185a79</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f5dd988-f80a-4019-b00f-9cc9981ace47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_CURA_Login_DD</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>721e7ace-d18a-4795-b5f9-2b7fb5653773</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32749cf3-7998-4650-b346-29ada4185a79</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
